version: 0.1.2.{build}
clone_depth: 1

environment:
    MSVC_DEFAULT_OPTIONS: ON
    matrix:
      - gen: "Visual Studio 15 2017"
        gen_short: 15
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      - gen: "Visual Studio 16 2019"
        gen_short: 16
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

init:
  - cmake --version

before_build:
  - git submodule update --init

build_script:
  - md debug_32
  - cd debug_32
  - cmake -G "%gen%" ..
  - cmake --build . --config Debug -- /maxcpucount
  - ctest -C Debug -V -j %NUMBER_OF_PROCESSORS%
  - cd ..

  - md release_32
  - cd release_32
  - cmake -G "%gen%" ..
  - cmake --build . --config Release -- /maxcpucount
  - ctest -C Release -V -j %NUMBER_OF_PROCESSORS%
  - cd ..

  - md debug_64
  - cd debug_64
  - if "%gen_short%" == "15" cmake -G "%gen% Win64" ..
  - if "%gen_short%" == "16" cmake -G "%gen%" -A "Win64" ..
  - cmake --build . --config Debug -- /maxcpucount
  - ctest -C Debug -V -j %NUMBER_OF_PROCESSORS%
  - cd ..

  - md release_64
  - cd release_64
  - if "%gen_short%" == "15" cmake -G "%gen% Win64" ..
  - if "%gen_short%" == "16" cmake -G "%gen%" -A "Win64" ..
  - cmake --build . --config Release -- /maxcpucount
  - ctest -C Release -V -j %NUMBER_OF_PROCESSORS%
  - cd ..

  - if "%gen_short%" == "16" md analysis
  - if "%gen_short%" == "16" cd analysis
  - if "%gen_short%" == "16" cmake -G "%gen%" -A "Win64" ..
  - if "%gen_short%" == "16" cmake --build . --config Debug -- /maxcpucount /p:RunCodeAnalysis=true
  - if "%gen_short%" == "16" cd ..
